### ISSUE TITLE
Mediator deployment with REDIS

### ISSUE THREAD

**Issue by esune** [bcgov/DITP-DevOps#75]
Deployment of an ACA-Py mediator with REDIS persistent queue plugin.

**Comment by WadeBarnes** [comment]
I've got the new persistent queue mediator tuned and stable. All pods in the mix have very low throttling percentages. 8% and lower for the Redis luster pods, and <1% for the mediator pods. I've also turned down the logging levels on ACA-Py to squeeze as much out of it as possible.  Invite provided to team.

I was getting some decent performance out of it this morning until the Locust container started to fall over.
![image](https://github.com/bcgov/DITP-DevOps/assets/10504350/b0ddeba3-ee3c-434c-80e1-acfb2abaa135)

Since then there's a few thousand more connection records in the secure storage and the performance is lower, but so far fairly stable.
![image](https://github.com/bcgov/DITP-DevOps/assets/10504350/873dfdc1-2021-4374-b779-f63f5348eb41)

I had to add a second CPU the mediator agent with the introduction of the Redis plugin. Without the second CPU the pod was going over allocation and being throttled over 60% of the time. Following the addition of the second CPU, throttling dropped to under 1%.

Longer run test results:
![image](https://github.com/bcgov/DITP-DevOps/assets/10504350/3fd4375f-0cf4-474d-929c-3becdb6afd0d)

[requests_1685035542.126043.csv](https://github.com/bcgov/DITP-DevOps/files/11567728/requests_1685035542.126043.csv)
[failures_1685035543.9566092.csv](https://github.com/bcgov/DITP-DevOps/files/11567729/failures_1685035543.9566092.csv)
[exceptions_1685035544.99205.csv](https://github.com/bcgov/DITP-DevOps/files/11567730/exceptions_1685035544.99205.csv)

**Comment by WadeBarnes** [comment]
A little bit of cleanup left to do.

**Comment by esune** [comment]
@WadeBarnes I believe this is complete. Can you please confirm/close?

**Comment by WadeBarnes** [comment]
Yes, complete now
